"""Rename full title to title suffix.

Revision ID: 11dbdc3ad17f
Revises: 4110af0898a1
Create Date: 2014-10-27 22:30:04.291462

"""

# revision identifiers, used by Alembic.
revision = '11dbdc3ad17f'
down_revision = '4110af0898a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('title_suffix', sa.String(length=50), nullable=True))
    op.drop_column('work', 'full_title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('full_title', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('work', 'title_suffix')
    ### end Alembic commands ###
