"""Add full title to work

Revision ID: 4110af0898a1
Revises: 6da38f6cd25
Create Date: 2014-10-27 21:46:41.169546

"""

# revision identifiers, used by Alembic.
revision = '4110af0898a1'
down_revision = '6da38f6cd25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('full_title', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'full_title')
    ### end Alembic commands ###
