"""Add created_at to Quote.

Revision ID: 6da38f6cd25
Revises: None
Create Date: 2014-10-15 16:20:58.318467

"""

# revision identifiers, used by Alembic.
revision = '6da38f6cd25'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'created_at')
    ### end Alembic commands ###
