"""Add collection models.

Revision ID: 16ecfbc42d74
Revises: 23a42397e880
Create Date: 2015-11-09 11:28:08.454078

"""

# revision identifiers, used by Alembic.
revision = '16ecfbc42d74'
down_revision = '23a42397e880'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('kind_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kind_id'], ['collection_kind.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collection_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'collect_work_image_ibfk_4', 'collect_work_image', type_='foreignkey')
    op.create_foreign_key(None, 'collect_work_image', 'work_image', ['work_image_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collect_work_image', type_='foreignkey')
    op.create_foreign_key(u'collect_work_image_ibfk_4', 'collect_work_image', 'work_image', ['work_image_id'], ['id'], ondelete=u'CASCADE')
    op.drop_table('collection_work')
    op.drop_table('collection')
    op.drop_table('collection_kind')
    ### end Alembic commands ###
