"""Update Collection model.

Revision ID: 2b37f5ee78de
Revises: 16ecfbc42d74
Create Date: 2015-11-09 11:40:51.977038

"""

# revision identifiers, used by Alembic.
revision = '2b37f5ee78de'
down_revision = '16ecfbc42d74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('cover', sa.String(length=200), nullable=True))
    op.add_column('collection', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('collection', sa.Column('link', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'link')
    op.drop_column('collection', 'desc')
    op.drop_column('collection', 'cover')
    ### end Alembic commands ###
