"""Update work.

Revision ID: 4934cae064bb
Revises: 508f9801867f
Create Date: 2015-10-18 12:57:53.085719

"""

# revision identifiers, used by Alembic.
revision = '4934cae064bb'
down_revision = '508f9801867f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('baidu_wiki', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'baidu_wiki')
    ### end Alembic commands ###
