"""Update collection model.

Revision ID: 4f8982b79976
Revises: 2b37f5ee78de
Create Date: 2015-11-09 14:09:41.339144

"""

# revision identifiers, used by Alembic.
revision = '4f8982b79976'
down_revision = '2b37f5ee78de'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('abbr', sa.String(length=50), nullable=True))
    op.add_column('collection', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.alter_column('collection', 'kind_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint(None, 'collection', ['full_name'])
    op.alter_column('collection_work', 'collection_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('collection_work', 'work_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_work', 'work_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('collection_work', 'collection_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'collection', type_='unique')
    op.alter_column('collection', 'kind_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('collection', 'full_name')
    op.drop_column('collection', 'abbr')
    ### end Alembic commands ###
