"""Add baidu_wiki to author.

Revision ID: 23a42397e880
Revises: 4934cae064bb
Create Date: 2015-10-23 10:55:43.255124

"""

# revision identifiers, used by Alembic.
revision = '23a42397e880'
down_revision = '4934cae064bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('baidu_wiki', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'baidu_wiki')
    ### end Alembic commands ###
