"""Rm work tag models.

Revision ID: 2469e89395b0
Revises: 4f3701cfea05
Create Date: 2015-11-28 12:25:12.125389

"""

# revision identifiers, used by Alembic.
revision = '2469e89395b0'
down_revision = '4f3701cfea05'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_tag')
    op.drop_table('tag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('desc', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=200), server_default=sa.text(u"'http://placehold.it/60x60'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('work_tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('work_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], name=u'work_tag_ibfk_2'),
    sa.ForeignKeyConstraint(['work_id'], [u'work.id'], name=u'work_tag_ibfk_1'),
    sa.PrimaryKeyConstraint('id', 'work_id', 'tag_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
